disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- multiple_closures_with_trailing_closure
- identifier_name
- cyclomatic_complexity
- function_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- weather/application/R.generated.swift
- weather/components/thirdparty
line_length: 210
